// <auto-generated />
namespace CollaborativeLearning.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class CET444 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CET444));
        
        string IMigrationMetadata.Id
        {
            get { return "201402081910152_CET444"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
